sudo : required
services:
  - docker

before_install:
  - docker build -t jayateerth1995/aws-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jayateerth1995/aws-react npm test

after_success:
  - docker build -t jayateerth1995/multi-client ./client
  - docker build -t jayateerth1995/multi-nginx ./nginx
  - docker build -t jayateerth1995/multi-server ./server
  - docker build -t jayateerth1995/multi-worker ./worker
  # login to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  
  # push images to docker hub
 
  - docker push jayateerth1995/multi-client
  - docker push jayateerth1995/multi-nginx
  - docker push jayateerth1995/multi-server
  - docker push jayateerth1995/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker-aws"
  env: "MultiDockerAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-066206643671"
  bucket_path: "multi-docker-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
